export const SET_APP_LOADING = 'SET_APP_LOADING';

export const SET_NAME = 'SET_NAME';
export const SET_FRIEND_REQUESTS = 'SET_FRIEND_REQUESTS';
export const SET_CONTACTS = 'SET_CONTACTS';

export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';