export const SET_APP_LOADING = 'SET_APP_LOADING';

export const SET_NAME = 'SET_NAME';
export const SET_OUTGOING_REQUESTS = 'SET_OUTGOING_REQUESTS';
export const SET_INCOMING_REQUESTS = 'SET_INCOMING_REQUESTS';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_FRIENDS = 'SET_FRIENDS';

export const ADD_OUTGOING_REQUEST = 'ADD_OUTGOING_REQUEST';

export const ADD_FRIEND = 'ADD_FRIEND';
export const DENY_FRIEND = 'DENY_FRIEND';